# Generated by Django 4.1.3 on 2022-12-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractusers',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
