# Generated by Django 4.1.3 on 2022-12-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_abstractusers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractusers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='abstractusers',
            name='last_name',
        ),
    ]
